## name: DarkSideOfTheMoon
## author: MurderFromMars
## license: GNU GPL
background            #000000
foreground            #fbfbfb
selection_background  #8cbac5
selection_foreground  #000000
cursor                #8cbac5
# Black, Gray, Silver, White
color0                #000000
color8                #fbfbfb
color7                #fbfbfb
color15               #fbfbfb
# Red
color1                #8cbac5
color9                #8cbac5
# Green
color2                #8cbac5
color10               #fbfbfb
# Yellow
color3                #8cbac5
color11               #fbfbfb
# Blue
color4                #8cbac5
color12               #fbfbfb
# Purple
color5                #8cbac5
color13               #fbfbfb
# Teal
color6                #8cbac5
color14               #fbfbfb
